# 配置文件加密key
jasypt:
  encryptor:
    password: root

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://139.199.19.82:3306/frame?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    # Jasypt加密 可到common-utils中找到 JasyptUtil 加解密工具类生成加密结果 格式为ENC(加密结果)
    password: ENC(RjoZ3TFEWyZL/fdwGYTmgw==)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
server:
  port: 8091

jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://139.199.19.82:3306/frame?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
  username: root
  password: root

jdbc2:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://118.123.16.211:3306/shentu?characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true
  username: root
  password: root