# 配置文件加密key
jasypt:
  encryptor:
    password: root
server:
  port: 8091

#这个属于自定义的属性，指定了一个路径，用于文件上传，注意要以/结尾
web:
  upload-path: D:/file/

#======================================springboot默认数据源
spring:
  datasource:
    url: jdbc:mysql://139.199.19.82:3306/frame?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    # Jasypt加密 可到common-utils中找到 JasyptUtil 加解密工具类生成加密结果 格式为ENC(加密结果)
    password: ENC(RjoZ3TFEWyZL/fdwGYTmgw==)
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    logSlowSql: true

#====================================自定义数据源
hikari:
  frame:
    jdbc-url: jdbc:mysql://139.199.19.82:3306/frame?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: ENC(RjoZ3TFEWyZL/fdwGYTmgw==)
    maximum-pool-size: 10
#    driverClassName: com.mysql.jdbc.Driver
  shentu:
    jdbc-url: jdbc:mysql://118.123.16.211:3306/shentu?characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true
    username: root
    password: ENC(mI1nzP/OCFW7Pf6UO+RQCjHh5z/VzG3V)
    maximum-pool-size: 10
#    driverClassName: com.mysql.jdbc.Driver